#!/bin/sh
# SCMA_DATA should refer to the directory in which SchizoMania data files are placed.
#SCMA_DATA=~/schizomania
#SCMA_DATA=/usr/local/schizomania
SCMA_DATA=.

# SCMA should refer to the directory in which SchizoMania executable files are placed.
SCMA_BIN=src

# SCMA_OPTIONS contains any command line options you would like to start SchizoMania with.
#SCMA_OPTIONS=""
#SCMA_OPTIONS="-u${HOME}/.schizomania -g debug_log.txt"
SCMA_OPTIONS="-u${HOME}/.schizomania -g log.txt"

# SYSTEM_NAME should be set to the name of your operating system.
#SYSTEM_NAME=Linux
SYSTEM_NAME=`uname -s`
cc
# MACHINE_NAME should be set to the name of your processor.
#MACHINE_NAME=i686
MACHINE_NAME=`uname -m`

case ${SYSTEM_NAME} in
Linux)
  SYSTEM_NAME=linux_
  ;;
*)
  SYSTEM_NAME=unknown_
  ;;
esac

case ${MACHINE_NAME} in
i486|i586|i686)
  MACHINE_NAME=
  ;;
x86_64|amd64)
  MACHINE_NAME=64_
  ;;
*)
  if [ ${SYSTEM_NAME} != native_ ]
  then
    SYSTEM_NAME=native_
  fi
  MACHINE_NAME=
  ;;
esac

if [ -x ${SCMA_BIN}/SchizoMania_Client ]
then
  SYSTEM_NAME=native_
  MACHINE_NAME=
fi

cd ${SCMA_DATA}
exec gdb -q --args ${SCMA_BIN}/SchizoMania_Client ${SCMA_OPTIONS} "$@"
